src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from long_task.views import home, get_status, run_task

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
    path('home/', home, name='task_home'),
    path('tasks/<task_id>/', get_status, name='get_status'),
    path('tasks/', run_task, name='run_task'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from .views import ExamDetailView, ExamResultDeleteView, ExamResultDetailView, ExamResultUpdateView
from .views import ExamListView
from .views import ExamResultCreateView
from .views import ExamResultQuestionView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/next/', ExamResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
]

src/quiz/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models


class BaseModel(models.Model):
    create_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 100

    class LEVEL(models.IntegerChoices):
        BASIC = (0, 'Basic')
        MIDDLE = (1, 'Middle')
        ADVANCED = (2, 'Advanced')

    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def q_count(self):
        return self.questions.count()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'exams'
        verbose_name = 'Exam'
        verbose_name_plural = 'Exams'


class Question(BaseModel):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=2048)
    image = models.ImageField(upload_to='questions/', null=True, blank=True)

    def __str__(self):
        return self.text

    class Meta:
        db_table = 'questions'
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    class Meta:
        db_table = 'choices'
        verbose_name = 'Choice'
        verbose_name_plural = 'Choices'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(get_user_model(), related_name='results', on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True, default=0)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = 'results'
        verbose_name = 'Result'
        verbose_name_plural = 'Results'

    def update_result(self, order_number, question, selected_choices):
        correct_choice = [choice.is_correct for choice in question.choices.all()]
        correct_answer = True
        for group in zip(selected_choices, correct_choice):
            correct_answer = correct_answer and (group[0] == group[1])
            # correct_answer &= (group[0] == group[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number

        if order_number == question.exam.questions.count():
            self.state = self.STATE.FINISHED

        self.save()

    def points(self):
        return max(0, self.num_correct_answers-self.num_incorrect_answers)

src/quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Choice


class QuestionInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):

        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):

            raise ValidationError(
                f'Questions count must be range '
                f'from {self.instance.QUESTION_MIN_LIMIT} '
                f'to {self.instance.QUESTION_MAX_LIMIT} inclusive'
            )

        order_num_list = []
        range_list = []
        for index, form in enumerate(self.forms):
            order_num_list.append(form.cleaned_data['order_num'])
            range_list.append(index + 1)
        sorted_order_num_list = sorted(order_num_list)
        if not (sorted_order_num_list == range_list and sorted_order_num_list[-1] <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError(
                f'Order number must not be from 1 to 100 and less than '
                f'{self.instance.QUESTION_MAX_LIMIT} inclusive'
            )


class ChoiceInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        num_correct_answers = sum(form.cleaned_data['is_correct'] for form in self.forms)

        if num_correct_answers == 0:
            raise ValidationError('You must select at least 1 option.')

        if num_correct_answers == len(self.forms):
            raise ValidationError('NOT allowed to select all options.')


class ChoiceForm(forms.ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Choice
        fields = ['text']


ChoicesFormSet = forms.modelformset_factory(
    model=Choice,
    form=ChoiceForm,
    extra=0
)

src/quiz/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic.list import MultipleObjectMixin
from django.core.cache import cache

from .forms import ChoicesFormSet
from .models import Exam
from .models import Question
from .models import Result


class ExamListView(LoginRequiredMixin, ListView):
    model = Exam
    template_name = 'exams/list.html'
    context_object_name = 'exams'


class ExamDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Exam
    template_name = 'exams/details.html'
    context_object_name = 'exam'
    pk_url_kwarg = 'uuid'
    paginate_by = 3

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        return context

    def get_queryset(self):
        return Result.objects.filter(
            exam=self.get_object(),
            user=self.request.user
        ).order_by('state', '-create_timestamp')


class ExamResultCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result = Result.objects.create(
            user=request.user,
            exam=Exam.objects.get(uuid=uuid),
            state=Result.STATE.NEW
        )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': result.uuid,
                    # 'order_num': 1
                }
            )
        )


class ExamResultQuestionView(LoginRequiredMixin, UpdateView):
    def get_params(self, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        # order_num = kwargs.get('order_num')
        order_num = Result.objects.filter(
            uuid=res_uuid,
            user=self.request.user
        ).values('current_order_number').first().get('current_order_number') + 1

        return uuid, res_uuid, order_num

    # def get_question(self, uuid, order_number):
    #     question = cache.get('question')
    #     if not question:
    #         question = Question.objects.get(
    #             exam__uuid=uuid,
    #             order_num=order_number
    #         )
    #         cache.set('question', question, 30)
    #
    #     return question

    def get_question(self, uuid, order_number):
        return Question.objects.get(
            exam__uuid=uuid,
            order_num=order_number
        )

    def get(self, request, *args, **kwargs):
        uuid, _, order_num = self.get_params(**kwargs)
        question = self.get_question(uuid, order_num)

        choices = ChoicesFormSet(queryset=question.choices.all())

        return render(request, 'exams/question.html', context={'question': question, 'choices': choices})

    def post(self, request, *args, **kwargs):
        uuid, res_uuid, order_num = self.get_params(**kwargs)

        question = self.get_question(uuid, order_num)

        choices = ChoicesFormSet(data=request.POST)
        selected_choices = ['is_selected' in form.changed_data for form in choices.forms]

        result = Result.objects.get(uuid=res_uuid)
        result.update_result(order_num, question, selected_choices)

        if result.state == Result.STATE.FINISHED:
            return HttpResponseRedirect(
                reverse(
                    'quiz:result_details',
                    kwargs={
                        'uuid': uuid,
                        'res_uuid': result.uuid
                    }
                )
            )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': res_uuid,
                    # 'order_num': order_num + 1
                }
            )
        )


class ExamResultDetailView(LoginRequiredMixin, DetailView):
    model = Result
    template_name = 'results/details.html'
    context_object_name = 'result'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=uuid)


class ExamResultUpdateView(LoginRequiredMixin, UpdateView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': res_uuid,
                }
            )
        )


class ExamResultDeleteView(LoginRequiredMixin, DeleteView):
    model = Result
    template_name = 'exams/delete_result.html'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        res_uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=res_uuid)

    def form_valid(self, form):
        success_url = reverse_lazy(
            'quiz:details',
            kwargs={'uuid': self.kwargs.get('uuid')}
        )
        self.object.delete()
        return HttpResponseRedirect(success_url)

src/quiz/templates/exams/delete_result.html
{% extends 'base.html' %}

{% block title %}
    Delete result
{% endblock %}

{% block header %}
    Are you sure you want to delete this session?
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <input class="btn btn-danger m-3" type="submit" value="Delete">
        <a class="btn btn-outline-primary m-3" href="{% url 'quiz:list' %}">Back to list</a>
    </form>
{% endblock %}

src/quiz/templates/exams/details.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}
    Details of exam
{% endblock %}

{% block header %}
    Exam: {{ exam.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Description</td>
                            <td>{{ exam.description }}</td>
                        </tr>
                        <tr>
                            <td>Count of questions</td>
                            <td>{{ exam.questions.count }}</td>
                        </tr>
                        <tr>
                            <td>Count of runs</td>
                            <td>{{ exam.results.count }}</td>
                        </tr>
                        <tr>
                            <td>The best result</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>The best user</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Last run</td>
                            <td>N/A</td>
                        </tr>
                    </tbody>
              </table>
            </div>
        </div>
        <div class="row">
            <form method="post"
                  class="d-flex justify-content-center mt-1 mb-2"
                  action="{% url 'quiz:result_create' exam.uuid %}">
                {% csrf_token %}
                <input class="btn btn-outline-success m-3" type="submit" value="START">
                <a class="btn btn-outline-primary m-3" href="{% url 'quiz:list' %}">Back to list</a>
            </form>
        </div>
        <div class="row">
{#            {% if result_list %}#}
            {% if object_list %}
                <table class="table table-striped table-hover">
                    <tr>
                        <th></th>
                        <th>Start date</th>
                        <th>Points</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
{#                    {% for result in result_list %}#}
                    {% for result in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ result.create_timestamp|date:'d-m-Y H:i' }}</td>
                        {% if result.num_correct_answers <= result.num_incorrect_answers %}
                            <td>0</td>
                        {% else %}
                            <td>{{ result.num_incorrect_answers|negative|add:result.num_correct_answers }}</td>
                        {% endif %}
                        <td>{{ result.get_state_display }}</td>
                        <td>
                            {% if result.state == result.STATE.NEW %}
                                <a class="btn btn-outline-warning" href="{% url 'quiz:result_update' exam.uuid result.uuid %}">
                                    Continue
                                </a>
                                <a class="btn btn-outline-danger" href="{% url 'quiz:result_delete' exam.uuid result.uuid %}">
                                    Remove
                                </a>
                            {% else %}
                                <a class="btn btn-outline-success" href="{% url 'quiz:result_details' exam.uuid result.uuid %}">
                                    View
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
        {% if is_paginated %}
            <div class="row content-center">
                {% include 'includes/paginator.html' %}
            </div>
        {% endif %}
    </div>
{% endblock %}

src/quiz/templates/exams/list.html
{% extends 'base.html' %}

{% block title %}
    Exam list
{% endblock %}

{% block header %}
    Exam list.
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quiz:details' uuid=exam.uuid %}">Details</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no tests yet!</p>
    {% endif %}
{% endblock %}

src/quiz/templates/exams/question.html
{% extends 'base.html' %}

{% load custom_filters custom_tags %}

{% block title %}
    Question {{ question.order_num }}
{% endblock %}

{% block header %}
    {{ question.text }}
{#    {% with question.order_num|add:-1|multi:100|dived:question.exam.q_count as level %}#}
    {% expression '(%1 - 1) * 100 // %2' question.order_num question.exam.q_count as level %}
    <div class="progress" role="progressbar" aria-label="Example with label" aria-valuenow="{{ level }}" aria-valuemin="0" aria-valuemax="100">
      <div class="progress-bar" style="width: {{ level }}%">{{ level }}%</div>
    </div>
{#    {% endwith %}#}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ choices.management_form }}
            {% for form in choices %}
                <div class="mt-1">
                    {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}">
                        {{ form.text.value }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-5">Дальше ></button>
        </form>
    </div>
{% endblock %}